server:
  port: 8083

management:
  endpoint:
    health:
      probes:
        enabled: true
      
minio:
  host: localhost
  port: 9000
  disable-tls: true
  access-key: WRc6I2ubSt9iZ0P6
  secret-key: AOm7m0CaFaeO5RW74jhzYEvxB6A0FK4P
  
organization:
  host: localhost
  port: 8082

spring:   
  servlet:    
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

---
server:
  port: 8083
  
management:
  endpoint:
    health:     
      probes:
        enabled: true

minio:
  host: localhost
  port: 9000
  disable-tls: true
  access-key: admin
  secret-key: password
    
organization:
  host: localhost
  port: 8082
              
spring:
  config:
    activate:
      on-profile: native
      
  servlet:    
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

---
server:
  port: 8083
  
management:
  endpoint:
    health:     
      probes:
        enabled: true

minio:
  host: uniovi-hl
  port: 9000
  disable-tls: true
  access-key: BLBZSkLGtFD63XmP
  secret-key: vY8jARXmV7tsp7HSmtuBPjzBy8BWG57s
    
organization:
  host: localhost
  port: 8082
              
spring:
  config:
    activate:
      on-profile: avib
      
  servlet:    
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB